### ISSUE TITLE
ALS marker lists

### ISSUE THREAD

**Issue by zhangpicb** [jackhump/ALS_SpinalCord_QTLs#2]
Dear @jackhump 

Thanks for your great code!

I want to make ALS marker list for may study.Input data in ``` ALS_marker_lists.Rmd ``` are not easy to be found.For example, kelly et al. data downloaded from  websites are not ``` kelley_marker_gene_fidelity_all_tissues_combined.tsv.gz ```.Some data are difficult to be downloaded.

It would be appreciated if you could release ``` ALS_marker_lists.Rmd ``` output RData.

Thanks  in advanced!

Best,
zhang

**Comment by jackhump** [comment]
Hi Zhang! This was a great idea. I've now uploaded all the marker gene sets that I created to the repository: https://github.com/jackhump/ALS_SpinalCord_QTLs/tree/master/markers 

I hope you find them useful in your research!

Jack
